### PR TITLE
DL4EPI

### PR DESCRIPTION
**Pull request by gcgibson**
So python can't run files (main.py) that aren't in the same directory as main.py (it's bad). So here is a version that works but it needs some cleaning

### CODE REVIEW

**Comment by gcgibson** [comment]
Okay it's much more cleaned up and ready to be merged!

**Comment by nickreich** [comment]
Can you add in the DL4EPI model, an active binding for a logical `fit_once` option? I've added this in the sarimaTDModel already, so you can see an example. It's an easy few lines of code to copy over and just makes it so that the information about "whether the model fits once at the beginning of the season or needs to refit every week" is stored in the model itself.

**Comment by nickreich** [comment]
Could you also add, maybe just as comments in your model file, what external/python dependencies the model has? Would like a stranger to be able to come to this file and understand what they need to install.

**Comment by gcgibson** [comment]
first part done!

**Pull request merged**
